backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('history/', TemplateView.as_view(template_name='history.html'), name='history'),
    path('detail/', TemplateView.as_view(template_name='detail.html'), name='detail'),
    path('detail/', TemplateView.as_view(template_name='detail.html'), name='detail'),
    path('login/', TemplateView.as_view(template_name='login.html'), name='login'),
]

backend/books/urls.py
from django.urls import path
from . import views


# path: /books/
urlpatterns = [
    
    path('', views.book_list, name='book_list'),
    path('create/', views.book_create, name='book_create'),
    path('update/<int:pk>/', views.book_update, name='book_update'),
    path('delete/<int:pk>/', views.book_delete, name='book_delete'),
]

backend/books/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

backend/books/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'publication_date', 'book_type', )

backend/books/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book
from .forms import BookForm
from django.http import JsonResponse
from django.template.loader import render_to_string


def save_book_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            books = Book.objects.all()
            data['html_book_list'] = render_to_string('books/includes/partial_book_list.html', {
                'books': books
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def book_list(request):
    books = Book.objects.all()
    return render(request, 'books/book_list.html', {'books': books})


def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
    else:
        form = BookForm()
    return save_book_form(request, form, 'books/includes/partial_book_create.html')


def book_update(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
    else:
        form = BookForm(instance=book)
    return save_book_form(request, form, 'books/includes/partial_book_update.html')


def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    data = dict()
    if request.method == 'POST':
        book.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        books = Book.objects.all()
        data['html_book_list'] = render_to_string('books/includes/partial_book_list.html', {
            'books': books
        })
    else:
        context = {'book': book}
        data['html_form'] = render_to_string('books/includes/partial_book_delete.html',
                                             context,
                                             request=request,
                                             )
    return JsonResponse(data)

backend/books/templates/books/book_list.html
{% extends 'base.html' %}

{% load static %}

{% block javascript %}
  <script src="{% static 'books/js/books.js' %}"></script>
{% endblock %}
{% block header %}
  {% include 'books/includes/header.html' %}
{% endblock %}

{% block content %}
<div class='container '>
  <h1 class="page-header">Books</h1>

  <p>
    <button type="button" class="btn btn-primary js-create-book" data-url="{% url 'book_create' %}">
      <span class="glyphicon glyphicon-plus"></span>
      New book
    </button> 
  </p>

  <table class="table" id="book-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Publication date</th>
        <th>Type</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% include 'books/includes/partial_book_list.html' %}
    </tbody>
  </table>

  <div class="modal fade" id="modal-book">
    <div class="modal-dialog">
      <div class="modal-content">

      </div>
    </div>
  </div>
</div>
{% endblock %}

backend/books/templates/books/includes/header.html
<nav class="navbar container-fluid bg-secondary">
    <div class="container d-flex justify-content-between w-100">
      <a class="navbar-brand d-block text-white" href="{% url 'home' %}">Leadplus</a>
     {% if not request.path == '/login/' %} 
     <a class="navbar-brand d-block text-white" href="#">Logout</a> 
     {% endif %}
    </div>
</nav>

backend/books/templates/books/includes/partial_book_create.html
<form method="post" action="{% url 'book_create' %}" class="js-book-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new book</h4>
  </div>
  <div class="modal-body">
    {% include 'books/includes/partial_book_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" id='btn-close-modal' data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create book</button>
  </div>
</form>

backend/books/templates/books/includes/partial_book_delete.html
<form method="post" action="{% url 'book_delete' book.id %}" class="js-book-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm book deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the book <strong>{{ book.title }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal" id='btn-close-modal'>Close</button>
    <button type="submit" class="btn btn-danger">Delete book</button>
  </div>
</form>

backend/books/templates/books/includes/partial_book_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {{ field|add_class:"form-control" }}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

backend/books/templates/books/includes/partial_book_list.html
{% for book in books %}
  <tr>
    <td>{{ book.id }}</td>
    <td>{{ book.title }}</td>
    <td>{{ book.author }}</td>
    <td>{{ book.get_book_type_display }}</td>
    <td>{{ book.publication_date }}</td>
    <td>{{ book.pages }}</td>
    <td>{{ book.price }}</td>
    <td style="width: 150px">
      <button type="button"
              class="btn btn-warning btn-sm js-update-book"
              data-url="{% url 'book_update' book.id %}">
        <span class="glyphicon glyphicon-pencil"></span> Edit
      </button>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-book"
              data-url="{% url 'book_delete' book.id %}">
        <span class="glyphicon glyphicon-trash"></span> Delete
      </button>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="8" class="text-center bg-warning">No book</td>
  </tr>
{% endfor %}

backend/books/templates/books/includes/partial_book_update.html
<form method="post" action="{% url 'book_update' form.instance.pk %}" class="js-book-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update book</h4>
  </div>
  <div class="modal-body">
    {% include 'books/includes/partial_book_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal" id='btn-close-modal'>Close</button>
    <button type="submit" class="btn btn-primary">Update book</button>
  </div>
</form>

backend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Leadplus Status Page</title>
    <link href="{% static 'styles/index.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  
  </head>
  <body>
    {% block header %}
      {% include 'includes/header.html' %}
    {% endblock %}
      {% block content %}
      {% endblock %}
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

backend/templates/detail.html
{% extends 'base.html' %} 

{% block content %}

<div class='container w-50'>
<div class="d-flex justify-content-center">
  <div class="detail w-75 mt-4">
    <div class="">
      <p class="center-text" style="font-size: 24.5px">
        HubSpot is currently unavailable for some customers
      </p>
    </div>
    <div class="" style="display: flex; margin-bottom: 24px">
      <div class="col-2">Resolved</div>
      <div style="text-align: justify; font-size: 14px">
        Sequence enrollment is now fully accessible. We've identified and
        addressed the root cause of the issue. The incident has been fully
        resolved and Sequence enrollment should be working properly. No data was
        lost. <br />
        <p style="opacity: 0.5">
          Posted 8 months ago. Jun 24, 2023 - 14:42 EDT
        </p>
      </div>
    </div>

    <div class="" style="display: flex; margin-bottom: 24px">
      <div class="col-2">Resolved</div>
      <div style="text-align: justify; font-size: 14px">
        Sequence enrollment is now fully accessible. We've identified and
        addressed the root cause of the issue. The incident has been fully
        resolved and Sequence enrollment should be working properly. No data was
        lost. <br />
        <p style="opacity: 0.5">
          Posted 8 months ago. Jun 24, 2023 - 14:42 EDT
        </p>
      </div>
    </div>

    <div class="" style="display: flex; margin-bottom: 24px">
      <div class="col-2">Resolved</div>
      <div style="text-align: justify; font-size: 14px">
        Sequence enrollment is now fully accessible. We've identified and
        addressed the root cause of the issue. The incident has been fully
        resolved and Sequence enrollment should be working properly. No data was
        lost. <br />
        <p style="opacity: 0.5">
          Posted 8 months ago. Jun 24, 2023 - 14:42 EDT
        </p>
      </div>
    </div>

    <div class="" style="display: flex; margin-bottom: 24px">
      <div class="col-2">Resolved</div>
      <div style="text-align: justify; font-size: 14px">
        Sequence enrollment is now fully accessible. We've identified and
        addressed the root cause of the issue. The incident has been fully
        resolved and Sequence enrollment should be working properly. No data was
        lost. <br />
        <p style="opacity: 0.5">
          Posted 8 months ago. Jun 24, 2023 - 14:42 EDT
        </p>
      </div>
    </div>
    <div>
      <input
        class="p-2"
        style="width: 100%; font-size: 12px"
        type="text"
        placeholder="This incident affected: GA4 Analytics featured"
      />
    </div>
  </div>
</div>
</class>

{% endblock content %}

backend/templates/history.html
{% extends 'base.html' %}

{% block content %}
<div class='container w-50'>
<!-- incident history -->
  <h2 class="mt-4">Return to home page</h2>
<div class="history d-flex justify-content-between">
  <!-- Filter Components -->
  <div class="dropdown">
    <button
      class="btn btn-secondary dropdown-toggle"
      type="button"
      data-bs-toggle="dropdown"
      aria-expanded="false"
    >
      Filter Components
    </button>
    <ul class="dropdown-menu">
      <input
        class="form-control"
        id="history__search"
        type="text"
        placeholder="Search.."
      />
      <li><a class="dropdown-item" href="#">Action</a></li>
      <li><a class="dropdown-item" href="#">Another action</a></li>
      <li><a class="dropdown-item" href="#">Something else here</a></li>
    </ul>
  </div>

  <!-- Slide -->
  <div>
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
      <button type="button" class="btn btn-sm bg-white border border-gray">
        <i class="fa-solid fa-angle-left" style="color: black"></i>
      </button>
      <button type="button" class="btn bg-white">
        <span class="fs-9">December 2023 to February 2024</span>
      </button>
      <button type="button" class="btn btn-sm bg-white border border-gray">
        <i class="fa-solid fa-angle-right" ="color:black"></i>
      </button>
    </div>
  </div>
</div>

<div class="history-items">
  <!-- History item -->
  <div class="history-item">
    <h3>May 2023</h3>
    <div class="d-flex flex-column gap-4">
      <div class="card">
        <div class="card-header history-item__title">Quote</div>
        <div class="card-body">
          <p class="history-item__desc">
            A well-known quote, contained in a blockquote element.
          </p>
          <span class="history-item__date">May 19, 16:33 - 16:33 EDT</span>
        </div>
      </div>
      <div class="card">
        <div class="card-header history-item__title">Quote</div>
        <div class="card-body">
          <p class="history-item__desc">
            A well-known quote, contained in a blockquote element.
          </p>
          <span class="history-item__date">May 19, 16:33 - 16:33 EDT</span>
        </div>
      </div>
    </div>
    <div class="mt-2">
      <button class="btn btn-white border border-black w-100">
        +2 Show All 2 Incidents
      </button>
    </div>
  </div>
  <!-- History item -->
  <div class="history-item">
    <h3>May 2023</h3>
    <div class="d-flex flex-column gap-4">
      <div class="card">
        <div class="card-header history-item__title">Quote</div>
        <div class="card-body">
          <p class="history-item__desc">
            A well-known quote, contained in a blockquote element.
          </p>
          <span class="history-item__date">May 19, 16:33 - 16:33 EDT</span>
        </div>
      </div>
      <div class="card">
        <div class="card-header history-item__title">Quote</div>
        <div class="card-body">
          <p class="history-item__desc">
            A well-known quote, contained in a blockquote element.
          </p>
          <span class="history-item__date">May 19, 16:33 - 16:33 EDT</span>
        </div>
      </div>
    </div>
    <div class="mt-2">
      <button class="btn btn-white border border-black w-100">
        +2 Show All 2 Incidents
      </button>
    </div>
  </div>
</div>
</div>

{% endblock content %}

backend/templates/home.html
{% extends 'base.html' %}
{% block content %}
 <!-- Aleart -->
 <div class='container w-50'>
 <div
 class="alert alert-primary d-flex justify-content-between alert-custom"
 role="alert"
>
 <span>All Systems Operational</span>
 <span>Refreshed less than 1 minute ago</span>
</div>

<!-- About this site -->
<div class="about-this-site">
 <h2 class="about-this-site__title">About this site</h2>
 <p class="about-this-site__content">
   Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam,
   reiciendis ipsum. Adipisci, dolorem ea dolor consequuntur suscipit
   veniam quia fugiat modi ut. Illum hic corporis dolorum cupiditate
   aperiam tenetur error?
 </p>
</div>

<!-- List items -->
<div class="items border rounded">
 <!-- Item operational-->
 <div
   class="d-flex justify-content-between align-items-center px-2 border-bottom items_item__operational"
 >
   <div class="p-2 d-flex gap-1">
     <span class="items__item__operational__icon"
       ><i class="fa-solid fa-circle-check"></i
     ></span>
     <div class="items__item__default__notice">
       <span>
         <!-- Icon -->
         Notice
       </span>
       <br />
       <span class="items__item__default__log"> No know issues </span>
     </div>
   </div>
   <div>
     <button class="btn btn-outline-dark btn-operational">
       Operational
     </button>
   </div>
 </div>
 <!-- Item maintenance-->
 <div
   class="d-flex justify-content-between align-items-center px-2 border-bottom"
 >
   <div class="p-2 d-flex gap-1">
     <span class="items__item__icon items__item__maintenance__icon"
       ><i class="fa-solid fa-clock"></i></span>
     <div class="items__item__notice">
       <span>
         <!-- Icon -->
         Notice
       </span>
       <br />
       <span class="items__item__default__log">
         1 issues
         <ul>
           <li>Hubspot is current bla...</li>
         </ul>
       </span>
     </div>
   </div>
   <div>
     <button class="btn btn-outline-dark btn-maintenance">
       Maintenance
     </button>
   </div>
 </div>
 <!-- Item partial outage-->
 <div
   class="d-flex justify-content-between align-items-center px-2 border-bottom"
 >
   <div class="p-2 d-flex gap-1">
     <span class="items__item__icon items__item__partial-outage__icon"
       ><i class="fa-solid fa-circle-exclamation"></i></span>
     <div
       class="items__item__notice items__item__partial-outage__notice"
     >
       <span>
         <!-- Icon -->
         Notice
       </span>
       <br />
       <span class="items__item__default__log">
         1 issues
         <ul>
           <li>Hubspot is current bla...</li>
         </ul>
       </span>
     </div>
   </div>
   <div>
     <button class="btn btn-outline-dark btn-partial-outage">
       Degrated
     </button>
   </div>
 </div>

 <!-- Item outage-->
 <div
   class="d-flex justify-content-between align-items-center px-2 border-bottom"
 >
   <div class="p-2 d-flex gap-1">
     <span class="items__item__icon items__item__partial-outage__icon"
       ><i class="fa-solid fa-triangle-exclamation"></i></span>
     <div
       class="items__item__notice items__item__partial-outage__notice"
     >
       <span>
         <!-- Icon -->
         Notice
       </span>
       <br />
       <span class="items__item__default__log">
         1 issues
         <ul>
           <li>Hubspot is current bla...</li>
         </ul>
       </span>
     </div>
   </div>
   <div>
     <button class="btn btn-outline-dark btn-partial-outage">
       Outage
     </button>
   </div>
 </div>
</div>
</div>
{% endblock content %}

backend/templates/includes/header.html
{% load static %}

<div class="container w-50 mt-5 d-flex flex-column gap-2">
  <!-- Header -->
  <div class="d-flex justify-content-between header align-items-center">
    <!-- Logo -->
    <div class="d-flex gap-2 align-items-center">
      <div>
        <div class="card header__logo">
          <img
            src="{% static 'images/logo.png' %}"
            class="card-img-top"
            alt="..."
          />
        </div>
      </div>
      <div class="header__vertical-line"></div>
      <!-- Title -->
      <h3 class="header__status">Status</h3>
    </div>
    <!-- Button -->
    
    {% if request.path == '/' %} 
      <a href="{% url 'history' %}">
        <button class="btn btn-danger header__btn">Past Incidents</button>
      </a>
    {% elif request.path == '/history/' or request.path == '/detail/' %} 
      <a href="{% url 'home' %}">
        <button class="btn btn-danger header__btn">Return to home page</button>
      </a>
    {% endif %}
    
  </div>
  <!-- Body -->
</div>

backend/templates/login.html
{% extends 'base.html' %} 
{% block header %} 
{% include 'books/includes/header.html' %} 
{% endblock header %} {% block content %}

<div class="container w-50" style='margin-top:200px'>
  <form action="" method='post'  class='d-flex justify-content-center' >
    <div class='shadow-lg bg-body rounded-2 py-4 px-2' style='width:70%'>
    <div class="mb-3 row">
        <label for="static_username" class="col-sm-2 col-form-label">Username</label>
        <div class="col-sm-10">
          <input type="text"  class="form-control-plaintext  border border-secondary px-2 rounded-1" id="static_username" name='username' value="email@example.com">
        </div>
      </div>
      <div class="mb-3 row">
        <label for="static_password" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
          <input type="password"  class="form-control-plaintext  border border-secondary px-2 rounded-1" name='password' id="static_password" value="email@example.com">
        </div>
      </div>
      <div class='d-flex justify-content-end'><button type='submit' class="btn btn-danger ">Login</button> </div>
    </div>
  </form>
</div>

{% endblock content %}